# Requires https://github.com/canthefason/go-watcher

FROM golang

WORKDIR /go/src/github.com/winded/tyomaa/frontend/generator

ENTRYPOINT /go/bin/watcher --watch github.com/winded/tyomaa/frontend/ --debug 