version: '3.6'
services:
  tyomaa-frontend:
    image: winded/tyomaa-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    ports:
     - "8000:80"
    environment:
      API_ENDPOINT: "http://localhost:9000"
      OUTPUT_DIR: "/output"
    volumes:
     - $GOPATH:/go:rw
  tyomaa-backend:
    image: winded/tyomaa-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    ports:
     - "9000:80"
    environment:
     - DB_HOST=db
    volumes:
     - $GOPATH:/go:rw

  db:
    image: postgres:alpine
    environment:
     - POSTGRES_DB=tyomaa
     - POSTGRES_USER=tyomaa
     - POSTGRES_PASSWORD=tyomaa
    volumes:
     - db-data:/var/lib/postgresql/data:rw

volumes:
  db-data: