version: '3.6'
services:
  tyomaa-frontend:
    container_name: tyomaa-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    ports:
     - "8000:80"
    environment:
      API_ENDPOINT: "http://localhost:9000/api"
    volumes:
     - ./frontend/src:/usr/src/app/src:rw
     - ./frontend/static:/usr/src/app/static:rw
     - ./frontend/dist:/usr/src/app/dist:rw
  tyomaa-backend:
    container_name: tyomaa-backend
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    ports:
     - "9000:80"
    environment:
      PORT: "80"
    volumes:
     - ./backend/src:/usr/src/app/src:rw
     - ./backend/tests:/usr/src/app/tests:rw
     - ./backend/dist:/usr/src/app/dist:rw